spring:
  application:
    name: reservation-service
  profiles:
    active: local

---
server:
  port: 19095

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres  # PostgreSQL URL
    driver-class-name: org.postgresql.Driver
    username: postgres  # PostgreSQL 기본 사용자명
    password: 1234  # PostgreSQL 비밀번호 (실제 비밀번호로 수정)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL Dialect
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: redis1234

common:
  jpa:
    enabled: true